const express = require("express");
const router = express.Router();
var TeleSignSDK = require("telesignsdk"); // import the module

// create the endpoint(URL) for send sms for specified user

router.post("/sendSMS", async (req, res, next) => {
	/*
        for sending sms , use TeleSignSdk package (module) and use its trial account 
    */
   //test

	const receiverPhoneNo = req.body.phoneNo; // get the reciever's phone no in request body to a variavk

	try {
		const customerId = "67D18FB0-CB55-4314-89AE-6B5493C10B65";
		const apiKey =
			"jhskmQo+4k9Y1BQpUARdzftA8prXNDMzwXMdFMNRFFdKGbB11zP+6u172GEeyrmj3azqCoTDau/N9q98LK1TSw==";

		/*
        customerID and APIKEYS are auto generated by telesign website - credentials to use this service
        (authentication details)
    */

		const rest_endpoint = "https://rest-api.telesign.com";
		const timeout = 10 * 1000; // 10 secs

		const client = new TeleSignSDK(
			customerId, // create a object with these properties
			apiKey,
			rest_endpoint,
			timeout // optional
			// userAgent
		);

		const message = "SENSOR WARNING MESSAGE ------ TAKE A ACTION SOON "; // message
		const messageType = "ARN"; // ARN = Alerts, Reminders, and Notifications; OTP = One time password; MKT = Marketing

		console.log("## MessagingClient.message ##");

		function messageCallback(error, responseBody) {
			/*
        this callback  function  executed after clinet.sms.message() function has finished executing
        */

			if (error === null) {
				// check message sent successfully
				console.log(
					`Messaging response for messaging phone number: ${receiverPhoneNo}` +
						` => code: ${responseBody["status"]["code"]}` +
						`, description: ${responseBody["status"]["description"]}`
				);

				res.json("send sms successfully"); // send json response
			} else {
				console.error("Unable to send message. " + error); // log the errors
			}
		}

		client.sms.message(messageCallback, receiverPhoneNo, message, messageType);
		/*
    call the sms.message() method in TeleSignSDK client object with a callback
    send message to given user phone no
    */
	} catch (e) {
		console.log(e);
	}
});

module.exports = router;
